
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
<<<<<<< HEAD
server:
  port: 8761
=======
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8761
  
  
>>>>>>> e61648a (fix: dockerize backend and frontend)
